authors:
  daveebbelaar:
    name: Dave Ebbelaar
    description: AI Engineer & Founder of Datalumina
    avatar: https://avatars.githubusercontent.com/u/34709402?s=400&u=93706427f5441fa0d10086a0bc1b6298b06534df&v=4
    url: https://www.linkedin.com/in/daveebbelaar/